services:
  db:
    image: postgres:17
    container_name: pathpipe-dev-database
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${NEST_DATABASE_USER}
      POSTGRES_PASSWORD: ${NEST_DATABASE_PASS}
      POSTGRES_DB: ${NEST_DATABASE_NAME}
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    container_name: pathpipe-dev-redis
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - dev-network

volumes:
  pgdata:
  redisdata:

networks:
  dev-network:
