import { CompanyIndustry } from '@repo/db/types/company/industry';

export const COMPANY_INDUSTRY_OPTIONS = [
  { value: CompanyIndustry.ADVERTISING, label: 'Advertising' },
  { value: CompanyIndustry.AEROSPACE, label: 'Aerospace' },
  { value: CompanyIndustry.AGRICULTURE, label: 'Agriculture' },
  { value: CompanyIndustry.AI, label: 'AI' },
  { value: CompanyIndustry.AIRLINES, label: 'Airlines' },
  { value: CompanyIndustry.ART, label: 'Art' },
  { value: CompanyIndustry.AUTOMOTIVE, label: 'Automotive' },
  { value: CompanyIndustry.BANKING, label: 'Banking' },
  { value: CompanyIndustry.BIOTECHNOLOGY, label: 'Biotechnology' },
  { value: CompanyIndustry.BLOCKCHAIN, label: 'Blockchain' },
  { value: CompanyIndustry.CHEMICALS, label: 'Chemicals' },
  { value: CompanyIndustry.CLOUD_COMPUTING, label: 'Cloud Computing' },
  { value: CompanyIndustry.CONSUMER_GOODS, label: 'Consumer Goods' },
  { value: CompanyIndustry.CYBERSECURITY, label: 'Cybersecurity' },
  { value: CompanyIndustry.EDUCATION, label: 'Education' },
  { value: CompanyIndustry.ENERGY, label: 'Energy' },
  { value: CompanyIndustry.ENTERTAINMENT, label: 'Entertainment' },
  { value: CompanyIndustry.FASHION, label: 'Fashion' },
  { value: CompanyIndustry.FINANCE, label: 'Finance' },
  { value: CompanyIndustry.FOOD_AND_BEVERAGE, label: 'Food & Beverage' },
  { value: CompanyIndustry.GAMING, label: 'Gaming' },
  { value: CompanyIndustry.GOVERNMENT, label: 'Government' },
  { value: CompanyIndustry.HEALTHCARE, label: 'Healthcare' },
  { value: CompanyIndustry.HOSPITALITY, label: 'Hospitality' },
  { value: CompanyIndustry.INSURANCE, label: 'Insurance' },
  { value: CompanyIndustry.INTERNET, label: 'Internet' },
  { value: CompanyIndustry.LEGAL, label: 'Legal' },
  { value: CompanyIndustry.LOGISTICS, label: 'Logistics' },
  { value: CompanyIndustry.MANUFACTURING, label: 'Manufacturing' },
  { value: CompanyIndustry.MEDIA, label: 'Media' },
  { value: CompanyIndustry.MINING, label: 'Mining' },
  { value: CompanyIndustry.NON_PROFIT, label: 'Non-Profit' },
  { value: CompanyIndustry.PHARMACEUTICALS, label: 'Pharmaceuticals' },
  { value: CompanyIndustry.REAL_ESTATE, label: 'Real Estate' },
  { value: CompanyIndustry.RETAIL, label: 'Retail' },
  { value: CompanyIndustry.ROBOTICS, label: 'Robotics' },
  { value: CompanyIndustry.SEMICONDUCTORS, label: 'Semiconductors' },
  { value: CompanyIndustry.SOFTWARE, label: 'Software' },
  { value: CompanyIndustry.SPACE, label: 'Space' },
  { value: CompanyIndustry.SPORTS, label: 'Sports' },
  { value: CompanyIndustry.TELECOMMUNICATIONS, label: 'Telecommunications' },
  { value: CompanyIndustry.TRANSPORTATION, label: 'Transportation' },
  { value: CompanyIndustry.TRAVEL, label: 'Travel' },
];
