import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { cookies } from 'next/headers';
import CookieBanner from '../../components/marketing/cookie-banner';
import { ThemeProvider } from '@/components/shared/providers/theme-provider';
// import { PostHogProvider } from '@/components/providers/posthog-provider';
import { CookieConsentProvider } from '@/components/shared/providers/cookie-consent-provider';
import { Space_Grotesk } from 'next/font/google';

import '@repo/ui/globals.css';
import { Toaster } from '@repo/ui/components/sonner';

export const metadata: Metadata = {
  title: 'Marketing',
  description: 'Generated by create next app',
};

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

type MarketingLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default async function MarketingLayout({
  children,
}: MarketingLayoutProps) {
  const cookieStore = await cookies();

  const initialConsent = cookieStore.get('cookieConsent')?.value === 'true';

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.className}`}>
        <ThemeProvider>
          <CookieConsentProvider initialConsent={initialConsent}>
            <>{children}</>
            <CookieBanner />
          </CookieConsentProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
