import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { ThemeProvider } from '@/components/shared/providers/theme-provider';
import { Space_Grotesk } from 'next/font/google';

import '@repo/ui/globals.css';
import { Toaster } from '@repo/ui/components/sonner';

export const metadata: Metadata = {
  title: 'App',
  description: 'Generated by create next app',
};

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

type AppLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default async function AppLayout({ children }: AppLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.className}`}>
        <ThemeProvider>
          <>{children}</>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
