name: '🔀 Pull Request Jobs'
on:
  pull_request:

permissions:
  contents: read

jobs:
  quality-checks:
    name: Quality Checks
    uses: ./.github/workflows/build-lint-test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      node-version: '22'
